import { BINDING_KINDS, GAP_REASONS, factId, profileId, variantId, capabilityId, type AnalysisContracts, type Resource, type Witness } from "./framework.ts";
import type { LegacySnapshot } from "../engine/types.ts";
import type { Site } from "./behavior.ts";
import { publicMetadataName } from "../repository/metadata-policy.ts";

function object(v: unknown, keys: string[]): Record<string, unknown> { if (!v || typeof v !== "object" || Array.isArray(v)) throw new Error("Invalid shared record"); const o = Object.fromEntries(Object.entries(v)); if (Object.keys(o).length !== keys.length || keys.some(k => !(k in o))) throw new Error("Unknown/missing shared field"); return o; }
function list(v: unknown, limit = 200000): unknown[] { if (!Array.isArray(v) || v.length > limit) throw new Error("Invalid shared collection"); return v; }
function text(v: unknown): string { if (typeof v !== "string" || !v || v.length > 16384 || v.includes("\0")) throw new Error("Invalid shared text"); return v; }
function integer(v: unknown): number { if (typeof v !== "number" || !Number.isSafeInteger(v) || v < 0) throw new Error("Invalid shared integer"); return v; }
function bool(v: unknown): boolean { if (typeof v !== "boolean") throw new Error("Invalid shared boolean"); return v; }
function one(v: unknown, values: readonly string[]): string { const s = text(v); if (!values.includes(s)) throw new Error("Unsupported shared enum"); return s; }
function strings(v: unknown, limit = 200000): string[] { const s = list(v, limit).map(text); if (new Set(s).size !== s.length) throw new Error("Duplicate shared values"); return s; }
function relative(v: unknown): string { const s = text(v); if (s !== "." && (s.startsWith("/") || s.includes("\\") || s.includes(":") || s.split("/").some(x => !x || x === "." || x === ".."))) throw new Error("Invalid shared relative path"); return s; }
const sensitivePath = /^(?:\.env(?:\..*)?|credentials(?:\..*)?|secrets?(?:\..*)?|id_(?:rsa|dsa|ecdsa|ed25519)(?:\..*)?|.*\.(?:pem|key|p12|pfx|keystore))$/i;
function sameSite(a: Site, b: Site): boolean { return (["file", "start", "end", "line", "endLine", "fileHash", "extractor", "evidenceKind"] as const).every(k => a[k] === b[k]); }
function hash(v: unknown): string { const s = text(v); if (!/^[a-f0-9]{64}$/.test(s)) throw new Error("Invalid shared hash"); return s; }
function mapRecords(value: unknown, keys: string[], limit = 200000): Map<string, Record<string, unknown>> { const records = list(value, limit).map(v => object(v, keys)), result = new Map<string, Record<string, unknown>>(); for (const r of records) { const id = text(r.id); if (result.has(id)) throw new Error("Duplicate shared ID"); result.set(id, r); } return result; }

/** No parser AST, repository reads or graph algorithm lives in this validator. */
export function validateAnalysis(value: unknown, snapshot: LegacySnapshot): AnalysisContracts {
  const hasProxies = !!value && typeof value === "object" && "developmentProxies" in value;
  const a = object(value, ["status", "projects", "resources", "profiles", "variants", "qualifications", "capabilities", "registrations", "bindings", "candidates", "gaps", "assumptions", ...(hasProxies ? ["developmentProxies"] : [])]);
  one(a.status, ["legacy-observations", "assessed"]);
  const filesByPath = new Map(snapshot.files.map(f => [f.path, f]));
  const importIds = new Set(snapshot.relationships.map(r => r.id));
  const declarationIds = new Set(snapshot.behavior.declarations.map(d => d.id));
  const handlersByIndex = new Map(snapshot.behavior.handlers.map(h => [h.route, h]));
  const resources = new Map<string, Resource>();
  for (const v of list(a.resources, 20000)) { const r = object(v, ["path", "hash", "bytes", "utf16Length", "lines", "encoding", "purpose"]), p = relative(r.path); hash(r.hash); integer(r.bytes); integer(r.utf16Length); if (!integer(r.lines) || integer(r.bytes) > 1048576 || integer(r.utf16Length) > integer(r.bytes)) throw new Error("Invalid source dimensions"); one(r.encoding, ["utf8", "legacy-decoded", "binary"]); if (r.encoding === "binary" && (r.purpose !== "framework-input" || r.utf16Length !== 0 || r.lines !== 1)) throw new Error("Invalid binary resource"); one(r.purpose, ["source", "metadata", "framework-input"]); if (r.encoding === "legacy-decoded" && (a.status !== "legacy-observations" || r.purpose !== "source")) throw new Error("Unqualified source decoding"); if (resources.has(p)) throw new Error("Duplicate shared resource"); if (p.split('/').slice(0, -1).some(part => part.startsWith('.') || ['node_modules','dist','build','out','coverage','target','bin','obj','vendor','generated','__generated__','venv','__pycache__','site-packages'].includes(part.toLowerCase())) || /^(?:\.env(?:\..*)?|credentials(?:\..*)?|secrets?(?:\..*)?|id_(?:rsa|dsa|ecdsa|ed25519)(?:\..*)?|.*\.(?:pem|key|p12|pfx|keystore))$/i.test(p.split('/').at(-1)!)) throw new Error('Denied shared resource path'); if (r.purpose === 'metadata' && !publicMetadataName(p.split('/').at(-1)!)) throw new Error('Unapproved metadata witness'); if (r.purpose === "framework-input" && !/\.(?:html|css|svg|png|jpe?g|gif|webp|ico|woff2?|ttf|mp4|webm|txt|json)$/.test(p)) throw new Error("Unsupported framework input"); resources.set(p, r as Resource); }
  for (const f of snapshot.files) { const r = resources.get(f.path); if (!r || r.hash !== f.hash || r.bytes !== f.bytes || r.lines !== f.lines || r.purpose !== "source") throw new Error("Source resource disagrees with file"); }
  for (const r of resources.values()) if (r.path.split("/").length > 64 || r.path.split("/").some(part => sensitivePath.test(part))) throw new Error("Denied shared resource path");
  if ([...resources.values()].reduce((sum, r) => sum + r.bytes, 0) > 128 * 1024 * 1024) throw new Error("Shared resource budget exceeded");
  for (const r of resources.values()) if (r.purpose === "source" && !filesByPath.has(r.path)) throw new Error("Unknown shared source");
  const profiles = mapRecords(a.profiles, ["id", "projectId", "resolverId", "semanticsVersion", "language"]);
  const variants = mapRecords(a.variants, ["id", "projectId", "profileId", "resolverId", "environment", "platform", "conditions", "configWitnesses"]);
  const projects = new Map<string, Record<string, unknown>>();
  for (const v of list(a.projects)) { const p = object(v, ["projectId", "languages", "profileIds", "extractors"]), id = relative(p.projectId); if (projects.has(id) || !snapshot.projects.some(x => x.path === id)) throw new Error("Unknown/duplicate shared project"); strings(p.languages); strings(p.extractors); for (const profile of strings(p.profileIds)) if (profiles.get(profile)?.projectId !== id) throw new Error("Dangling project profile"); projects.set(id, p); }
  if (projects.size !== snapshot.projects.length) throw new Error("Missing shared project metadata");
  for (const p of profiles.values()) { const project = relative(p.projectId), resolver = text(p.resolverId), semantics = text(p.semanticsVersion); text(p.language); if (!projects.has(project) || !(projects.get(project)!.profileIds as string[]).includes(text(p.id)) || p.id !== profileId(project, resolver, semantics)) throw new Error("Invalid profile identity"); }
  for (const v of variants.values()) { const profile = profiles.get(text(v.profileId)); const environment = text(v.environment), platform = v.platform === null ? null : text(v.platform), conditions = strings(v.conditions, 100); if (!profile || v.projectId !== profile.projectId || v.resolverId !== profile.resolverId || v.id !== variantId(text(v.profileId), environment, platform, conditions)) throw new Error("Invalid variant identity"); }
  function site(value: unknown): Site { const s = object(value, ["file", "start", "end", "line", "endLine", "fileHash", "extractor", "evidenceKind"]), r = resources.get(relative(s.file)); const start = integer(s.start), end = integer(s.end), line = integer(s.line), endLine = integer(s.endLine); if (!r || s.fileHash !== r.hash || s.evidenceKind !== "verified" || !line || endLine < line || endLine > r.lines || end <= start || end > r.utf16Length) throw new Error("Invalid shared source range/hash"); text(s.extractor); return s as Site; }
  function witnesses(value: unknown, variant: string, requireSource = true): Witness[] { const result: Witness[] = []; for (const valueItem of list(value, 200)) { if (!valueItem || typeof valueItem !== "object") throw new Error("Invalid witness"); const role = (valueItem as Record<string, unknown>).role; if (role === "framework-rule") { const w = object(valueItem, ["role", "tupleId", "ruleId", "extractor", "extractorVersion", "variantId"]); text(w.tupleId); text(w.ruleId); text(w.extractor); text(w.extractorVersion); if (w.variantId !== variant) throw new Error("Witness variant mismatch"); result.push(w as Witness); } else { const w = object(valueItem, ["site", "extractorVersion", "role", "variantId"]); const location = site(w.site); one(w.role, ["declaration", "registration", "reference", "configuration"]); text(w.extractorVersion); if (w.variantId !== variant || (w.role === "configuration" && resources.get(location.file)?.purpose !== "metadata" && !filesByPath.has(location.file))) throw new Error("Witness variant/resource mismatch"); result.push(w as Witness); } } if (requireSource && !result.some(w => w.role !== "framework-rule")) throw new Error("Missing source witness"); return result; }
  for (const v of variants.values()) witnesses(v.configWitnesses, text(v.id), false);
  const gaps = mapRecords(a.gaps, ["id", "reason", "occurrence", "variantId", "capabilityId"]);
  const capabilities = mapRecords(a.capabilities, ["id", "tupleId", "capabilityId", "profileId", "variantId", "state", "extractorVersion", "qualificationRecord", "gapIds"]);
  const qualifications = mapRecords(a.qualifications, ["id", "tupleId", "capabilityId", "profileId", "variantId", "extractorVersion", "status", "fixtureIds", "outputHashes", "gates"]);
  const registrations = mapRecords(a.registrations, ["id", "kind", "handlerId", "variantId", "occurrence", "rawPattern", "methodState", "matcher", "precedence", "conditions", "prefixWitnesses", "witnesses", "legacyRouteIndex", "gapIds"], 10000);
  const bindings = mapRecords(a.bindings, ["id", "kind", "sourceId", "targetId", "variantId", "occurrence", "witnesses"]);
  const candidates = mapRecords(a.candidates, ["id", "relationKind", "sourceId", "targetIds", "reasons", "truncated", "variantId", "occurrence", "witnesses"]);
  const assumptions = mapRecords(a.assumptions, ["id", "revision", "variantId", "service", "origin", "provenance"]);
  const allIds = [...profiles.keys(), ...variants.keys(), ...gaps.keys(), ...capabilities.keys(), ...qualifications.keys(), ...registrations.keys(), ...bindings.keys(), ...candidates.keys(), ...assumptions.keys()];
  if (allIds.length > 200000) throw new Error("Shared fact budget exceeded");
  if (new Set(allIds).size !== allIds.length || allIds.some(id => importIds.has(id) || filesByPath.has(id) || declarationIds.has(id))) throw new Error("Colliding shared identity");
  const declarations = new Map(snapshot.behavior.declarations.map(d => [d.id, d]));
  const target = (id: unknown) => { const s = text(id); if (!filesByPath.has(s) && resources.get(s)?.purpose !== "framework-input" && !declarations.has(s) && !registrations.has(s)) throw new Error("Dangling shared target"); return s; };
  const variant = (id: unknown) => { const s = text(id); if (!variants.has(s)) throw new Error("Unsupported shared variant"); return s; };
  const gapRefs = (value: unknown, variantId: string) => { const ids = strings(value); for (const id of ids) if (gaps.get(id)?.variantId !== variantId) throw new Error("Dangling/cross-variant gap"); return ids; };
  for (const g of gaps.values()) { const v = variant(g.variantId), s = site(g.occurrence), reason = one(g.reason, GAP_REASONS); if (g.id !== factId("gap", s, v, reason) || (g.capabilityId !== null && capabilities.get(text(g.capabilityId))?.variantId !== v)) throw new Error("Invalid gap identity/capability"); }
  for (const q of qualifications.values()) { const v = variant(q.variantId); if (variants.get(v)?.profileId !== q.profileId) throw new Error("Dangling qualification profile"); for (const key of ["tupleId", "capabilityId", "profileId", "extractorVersion"]) text(q[key]); if (q.status !== "complete" || !strings(q.fixtureIds).length || !strings(q.outputHashes).length) throw new Error("Incomplete qualification ledger"); for (const h of q.outputHashes as string[]) hash(h); const gates = object(q.gates, ["positive", "negative", "windows"]); if (Object.values(gates).some(v => v !== true)) throw new Error("Missing qualification gate"); }
  for (const c of capabilities.values()) { const v = variant(c.variantId); for (const key of ["tupleId", "capabilityId", "profileId", "extractorVersion"]) text(c[key]); if (variants.get(v)?.profileId !== c.profileId || c.id !== capabilityId(c as Parameters<typeof capabilityId>[0])) throw new Error("Invalid capability identity/profile"); const state = one(c.state, ["qualified", "partial", "unsupported", "blocked"]); gapRefs(c.gapIds, v); if (c.qualificationRecord !== null) { const q = qualifications.get(text(c.qualificationRecord)); if (!q || ["tupleId", "capabilityId", "profileId", "variantId", "extractorVersion"].some(key => q[key] !== c[key])) throw new Error("Qualification tuple mismatch"); } if (state === "qualified" && c.qualificationRecord === null) throw new Error("Unqualified capability claim"); }
  const legacyIndices = new Set<number>();
  for (const r of registrations.values()) { const v = variant(r.variantId), s = site(r.occurrence), kind = one(r.kind, ["http", "page", "navigation"]); if (r.id !== factId("registration:" + kind, s, v, r.legacyRouteIndex === null ? text(r.rawPattern) : JSON.stringify([text(r.rawPattern), snapshot.routes[integer(r.legacyRouteIndex)]?.method]))) throw new Error("Invalid registration identity"); const proof = witnesses(r.witnesses, v); if (!proof.some(w => w.role === "registration" && sameSite(w.site, s))) throw new Error("Registration occurrence missing from proof"); if (r.handlerId !== null && !declarations.get(text(r.handlerId))?.callable) throw new Error("Wrong endpoint handler type"); if (r.handlerId !== null && !proof.some(w => w.role === "declaration" && sameSite(w.site, declarations.get(String(r.handlerId))!.site))) throw new Error("Missing handler declaration witness"); const refs = gapRefs(r.gapIds, v); if (r.handlerId === null && !refs.length) throw new Error("Unbound registration has no gap"); if (r.precedence !== null) integer(r.precedence); strings(r.conditions); witnesses(r.prefixWitnesses, v, false);
    if (kind !== "http") { if (r.methodState !== null) throw new Error("Navigation is not HTTP"); } else { if (!r.methodState || typeof r.methodState !== "object") throw new Error("HTTP method state missing"); const raw = r.methodState as Record<string, unknown>, state = one(raw.state, ["known", "unknown", "all", "dispatch-dependent"]); const m = object(raw, state === "dispatch-dependent" ? ["state", "values", "gapId"] : ["state", "values"]), values = strings(m.values, 100); if (state === "known" ? !values.length || values.some(x => !/^[A-Z]+$/.test(x)) : values.length > 0) throw new Error("Invalid method values"); if (state === "unknown" && !refs.some(id => gaps.get(id)?.reason === "unknown-method")) throw new Error("Unknown method lacks gap"); if (state === "dispatch-dependent" && (!refs.includes(text(m.gapId)) || gaps.get(String(m.gapId))?.reason !== "unknown-method")) throw new Error("Dispatch method lacks gap"); }
    const rawMatcher = r.matcher as Record<string, unknown>; if (!rawMatcher || typeof rawMatcher !== "object") throw new Error("Invalid matcher"); if (rawMatcher.state === "unsupported") { const m = object(rawMatcher, ["state", "gapId"]); if (!refs.includes(text(m.gapId)) || gaps.get(String(m.gapId))?.reason !== "unsupported-matcher") throw new Error("Unsupported matcher lacks gap"); } else { const m = object(rawMatcher, ["state", "segments", "trailingSlash", "caseSensitive", "decodingPolicy"]); if (m.state !== "supported") throw new Error("Invalid matcher state"); one(m.trailingSlash, ["required", "forbidden", "optional"]); bool(m.caseSensitive); one(m.decodingPolicy, ["raw", "percent-decode-segments"]); const names = new Set<string>(); const segments = list(m.segments, 64); segments.forEach((value, index) => { const raw = value as Record<string, unknown>; if (!raw || typeof raw !== "object") throw new Error("Invalid segment"); const k = one(raw.kind, ["literal", "parameter", "catchAll"]), segment = object(raw, k === "literal" ? ["kind", "value"] : k === "parameter" ? ["kind", "name", "converter"] : ["kind", "name", "optional"]); if (k === "literal") { if (text(segment.value).includes("/")) throw new Error("Segment contains slash"); } else { const name = text(segment.name); if (names.has(name)) throw new Error("Duplicate route parameter"); names.add(name); if (k === "parameter") one(segment.converter, ["segment", "integer", "uuid", "slug"]); else { bool(segment.optional); if (index !== segments.length - 1) throw new Error("Catch-all is not terminal"); } } }); }
    if (r.legacyRouteIndex !== null) { const index = integer(r.legacyRouteIndex), route = snapshot.routes[index], handler = handlersByIndex.get(index); if (legacyIndices.has(index) || !route || !handler || route.file !== s.file || route.pattern !== r.rawPattern || handler.target !== r.handlerId || !sameSite(handler.site, s)) throw new Error("Invalid legacy registration projection"); legacyIndices.add(index); }
  }
  if (legacyIndices.size !== snapshot.routes.length) throw new Error("Missing legacy registration projection");
  function owned(sourceId: unknown, occurrence: Site, variantId: string) { const id = target(sourceId), owner = declarations.get(id), registration = registrations.get(id); if (registration && (registration.variantId !== variantId || !sameSite(site(registration.occurrence), occurrence))) throw new Error("Registration source scope mismatch"); if ((filesByPath.has(id) || resources.get(id)?.purpose === "framework-input") && id !== occurrence.file || owner && (owner.site.file !== occurrence.file || owner.site.start > occurrence.start || owner.site.end < occurrence.end)) throw new Error('Source ownership mismatch'); }
  const kinds = BINDING_KINDS;
  for (const binding of bindings.values()) {
    const kind=String(binding.kind),targetId=String(binding.targetId);
    if (["module-dependency","worker"].includes(kind) && !filesByPath.has(targetId)
      || kind === "entry-point" && !filesByPath.has(targetId) && !declarations.has(targetId)
      || kind === "asset" && !filesByPath.has(targetId) && resources.get(targetId)?.purpose !== "framework-input") throw new Error("Wrong framework resource target");
  }
  for (const b of bindings.values()) { const v = variant(b.variantId), s = site(b.occurrence), kind = one(b.kind, kinds); owned(b.sourceId, s, v); const t = target(b.targetId); if (b.id !== factId("binding:" + kind, s, v, t)) throw new Error("Invalid binding identity"); const proof = witnesses(b.witnesses, v); if (!proof.some(w => w.role !== 'framework-rule' && sameSite(w.site, s))) throw new Error('Binding occurrence missing from proof'); if (declarations.has(t) && !proof.some(w => w.role === 'declaration' && sameSite(w.site, declarations.get(t)!.site))) throw new Error('Missing binding declaration witness'); if (['event-handler','lifecycle','native-bridge'].includes(kind) && !declarations.get(t)?.callable) throw new Error('Noncallable framework binding'); if (kind === 'registration' && !registrations.has(t) || kind === 'navigation' && (!registrations.has(t) || registrations.get(t)!.kind === 'http')) throw new Error('Wrong framework endpoint kind'); if (registrations.has(t) && registrations.get(t)!.variantId !== v) throw new Error("Cross-variant binding"); }
  for (const c of candidates.values()) { const v = variant(c.variantId), s = site(c.occurrence), kind = one(c.relationKind, [...kinds, "request-endpoint"]); owned(c.sourceId, s, v); for (const t of strings(c.targetIds, 200)) { target(t); if (kind === "request-endpoint" && registrations.get(t)?.kind !== "http") throw new Error("Wrong candidate endpoint kind"); if (registrations.has(t) && registrations.get(t)!.variantId !== v) throw new Error("Cross-variant candidate"); } const reasons = strings(c.reasons, GAP_REASONS.length); if (!reasons.length) throw new Error("Candidate missing uncertainty"); for (const reason of reasons) one(reason, GAP_REASONS); bool(c.truncated); if (c.truncated && !reasons.includes("candidate-overflow")) throw new Error("Truncation missing reason"); if (c.id !== factId("candidate:" + kind, s, v, text(c.sourceId))) throw new Error("Invalid candidate identity"); const proof = witnesses(c.witnesses, v); if (!proof.some(w => w.role !== "framework-rule" && sameSite(w.site, s))) throw new Error("Candidate occurrence missing from proof"); }
  for (const x of assumptions.values()) { variant(x.variantId); if (!integer(x.revision) || x.provenance !== "user") throw new Error("Invalid assumption provenance"); text(x.service); const url = new URL(text(x.origin)); if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.origin !== x.origin) throw new Error("Invalid assumed origin"); }
  for (const raw of hasProxies ? list(a.developmentProxies, 64) : []) {
    const p = object(raw,["id","variantId","scope","prefix","targetOrigin","targetBasePath","rewrite","occurrence","witnesses"]), v = variant(p.variantId), s = site(p.occurrence);
    if (p.scope !== "development" || !/^vite\.config\.[cm]?[jt]s$/.test(s.file.split("/").at(-1)!) || !["metadata","source"].includes(resources.get(s.file)?.purpose ?? "") || !text(p.prefix).startsWith("/") || !text(p.targetBasePath).startsWith("/")) throw new Error("Invalid development routing scope");
    const origin = new URL(text(p.targetOrigin));
    if (!["http:","https:"].includes(origin.protocol) || origin.origin !== p.targetOrigin || origin.username || origin.password) throw new Error("Invalid proxy origin");
    const identity = text(p.id);
    if (identity !== factId("development-proxy",s,v,text(p.prefix)) || allIds.includes(identity)) throw new Error("Invalid proxy identity");
    allIds.push(identity);
    const proof = witnesses(p.witnesses,v);
    if (!proof.some(w=>w.role === "configuration" && sameSite(w.site,s))) throw new Error("Missing proxy configuration proof");
    const rewrite = p.rewrite as Record<string,unknown>;
    if (!rewrite || typeof rewrite !== "object") throw new Error("Invalid proxy rewrite");
    if (rewrite.state === "identity") object(rewrite,["state"]);
    else if (rewrite.state === "prefix") {object(rewrite,["state","from","to"]); if (!text(rewrite.from).startsWith("/") || typeof rewrite.to !== "string" || rewrite.to.length > 16384 || rewrite.to.includes("\0")) throw new Error("Invalid prefix rewrite");}
    else if (rewrite.state === "unknown") {object(rewrite,["state","gapId"]); if (gaps.get(text(rewrite.gapId))?.variantId !== v) throw new Error("Missing proxy rewrite gap");}
    else throw new Error("Invalid proxy rewrite state");
  }
  if (allIds.length > 200000) throw new Error("Shared fact budget exceeded");
  return structuredClone(a) as AnalysisContracts;
}
