import assert from "node:assert/strict";
import path from "node:path";
import {tmpdir} from "node:os";
import {mkdtempSync,realpathSync,mkdirSync,readFileSync,writeFileSync,rmSync,cpSync} from "node:fs";
import {execFileSync} from "node:child_process";
import {pathToFileURL} from "node:url";
import {createHash} from "node:crypto";
const staged=path.resolve("src-tauri/resources/generated/engine"),runtime=JSON.parse(readFileSync(path.join(staged,"runtime.json"),"utf8"));
const directory=realpathSync.native(mkdtempSync(path.join(tmpdir(),"cartograph FS04 packaged ")));
const resources=path.join(directory,"engine"),executable=path.join(directory,"code-engine.exe");
cpSync(staged,resources,{recursive:true});cpSync(path.resolve(`src-tauri/binaries/code-engine-${runtime.target}.exe`),executable);
const fixtureBytes=readFileSync("tests/fixtures/framework-support/F04-node-next/fixture.json"),sources:Record<string,string>=JSON.parse(fixtureBytes.toString()).sources;
const moduleUrl=(file:string)=>JSON.stringify(pathToFileURL(path.join(resources,file)).href),results=[];
try {
  for(const [tuple,next] of [["next15","15.5.27"],["next16-preservation","16.3.6"],["next16-patch","16.3.8"]]) {
    const root=path.join(directory,tuple);mkdirSync(root);
    for(const [file,text]of Object.entries(sources)){mkdirSync(path.dirname(path.join(root,file)),{recursive:true});writeFileSync(path.join(root,file),file==="package.json" ? text.replace("16.3.8",next).replace("24.19.0",next==="15.5.27" ? "22.23.3" : "24.19.0") : text);}
    const probe=`
      import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {writeFileSync} from 'node:fs';import net from 'node:net';import {createRequire} from 'node:module';const resolveTool=createRequire(import.meta.url);for(const tool of ['next','react','typescript','pnpm'])assert.throws(()=>resolveTool.resolve(tool),{code:'MODULE_NOT_FOUND'});
      const {createTypescriptRefresh}=await import(${moduleUrl("lib/engine/adapters/typescript.ts")});
      const {readWitnessEvidence}=await import(${moduleUrl("lib/engine/index.ts")});
      const {traceFramework}=await import(${moduleUrl("lib/engine/behavior.ts")});
      const {SqliteAnalysisStore}=await import(${moduleUrl("lib/storage/sqlite.ts")});
      globalThis.fetch=async()=>{throw Error('denied egress')};net.connect=()=>{throw Error('denied egress')};net.createConnection=net.connect;
      const root=${JSON.stringify(root)},driver=createTypescriptRefresh({nodeModes:['node-development','node-production','browser']}),snapshot=driver.analyze(root,true).snapshot;
      const variants=snapshot.analysis.variants.filter(v=>v.resolverId==='next-runtime');assert.equal(variants.length,3);
      for(const v of variants){assert(snapshot.analysis.registrations.some(r=>r.variantId===v.id&&r.rawPattern==='/base/api/items/[id]'&&r.methodState?.state==='known'));const trace=traceFramework(snapshot,'app/page.tsx',v.id,12,200);assert(trace.steps.some(s=>s.kind==='framework-binding'&&s.binding.kind==='server-action'));assert(trace.steps.some(s=>s.kind==='verified-call'));}
      const witnesses=[...new Map(snapshot.analysis.bindings.flatMap(b=>b.witnesses).map(w=>[JSON.stringify(w),w])).values()];for(const w of witnesses)assert(['rule','current'].includes(readWitnessEvidence(snapshot,w).state));
      assert.deepEqual(driver.analyze(root,false).snapshot,snapshot);
      const db=${JSON.stringify(path.toNamespacedPath(path.join(directory,tuple+".sqlite")))};let store=new SqliteAnalysisStore(db);const repo=store.register(root);store.begin(repo.repositoryId,'fs04');store.publish(repo.repositoryId,'fs04',snapshot);store.close();store=new SqliteAnalysisStore(db);assert.deepEqual(store.load(repo.repositoryId),snapshot);store.close();
      const witness=snapshot.analysis.bindings.find(b=>b.occurrence.file==='app/page.tsx').witnesses.find(w=>w.role!=='framework-rule'&&w.site.file==='app/page.tsx');writeFileSync(root+'/app/page.tsx','export default function Page(){return <div/>}');assert.equal(readWitnessEvidence(snapshot,witness).state,'stale');
      console.log(JSON.stringify({tuple:${JSON.stringify(tuple)},node:process.version,profiles:variants.map(v=>v.environment),files:snapshot.files.length,bindings:snapshot.analysis.bindings.length,registrations:snapshot.analysis.registrations.length,distinctWitnesses:witnesses.length,extractorVersion:'fs-04/1',snapshotHash:createHash('sha256').update(JSON.stringify(snapshot)).digest('hex'),rssBytes:process.memoryUsage().rss,checks:['offline','empty PATH','development tooling absent','three profiles','UI-action-call trace','witnesses current/stale','full/incremental','SQLite reopen']}));
    `;
    results.push(JSON.parse(execFileSync(executable,["--disable-warning=ExperimentalWarning","--input-type=module","--eval",probe],{cwd:resources,env:{PATH:"",NODE_ENV:"production",SystemRoot:process.env.SystemRoot,TEMP:process.env.TEMP,TMP:process.env.TMP},encoding:"utf8",timeout:120000})));
  }
  const nodeBytes=readFileSync("tests/fixtures/framework-support/F04-node-next/node.json"),nativeSources:Record<string,string>=JSON.parse(nodeBytes.toString()).sources;
  nativeSources["jsx.mjs"]="import {createServer} from 'node:http';function handler(){return <div/>}const server=createServer(handler);";nativeSources["typed.ts"]="import type {Missing} from './missing.ts';export function typed(value:number):number{return value}";nativeSources["duplicate.cjs"]="function first(){}function second(){}exports.handler=first;module.exports.handler=second;";const nativePackage=JSON.parse(nativeSources["package.json"]);nativePackage.bin.typed="./typed.ts";nativeSources["package.json"]=JSON.stringify(nativePackage);
  for(const [tuple,version]of [["node22","22.23.3"],["node24","24.19.0"]]){
    const root=path.join(directory,tuple);mkdirSync(root);for(const [file,text]of Object.entries(nativeSources))writeFileSync(path.join(root,file),file==="package.json" ? text.replace("24.19.0",version) : text);
    const probe=`import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import net from 'node:net';import {createRequire} from 'node:module';const resolveTool=createRequire(import.meta.url);for(const tool of ['next','react','typescript','pnpm'])assert.throws(()=>resolveTool.resolve(tool),{code:'MODULE_NOT_FOUND'});const {createTypescriptRefresh}=await import(${moduleUrl("lib/engine/adapters/typescript.ts")});globalThis.fetch=async()=>{throw Error('denied egress')};net.connect=()=>{throw Error('denied egress')};net.createConnection=net.connect;const driver=createTypescriptRefresh({nodeModes:['node-development','node-production']}),s=driver.analyze(${JSON.stringify(root)},true).snapshot;for(const kind of ['module-dependency','module-export','worker','event-handler','operation','entry-point'])assert(s.analysis.bindings.some(b=>b.kind===kind));assert(s.analysis.gaps.some(g=>g.occurrence.file==='main.cjs'&&g.reason==='missing-metadata'));assert(s.analysis.bindings.some(b=>b.kind==='entry-point'&&b.targetId==='typed.ts'));assert(!s.analysis.bindings.some(b=>b.kind==='module-dependency'&&b.occurrence.file==='typed.ts'));assert(!s.analysis.bindings.some(b=>b.kind==='module-export'&&b.occurrence.file==='duplicate.cjs'));assert(!s.analysis.bindings.some(b=>b.occurrence.file==='jsx.mjs'));assert(s.analysis.gaps.some(g=>g.occurrence.file==='jsx.mjs'&&g.reason==='unsupported-syntax'));assert.deepEqual(driver.analyze(${JSON.stringify(root)},false).snapshot,s);console.log(JSON.stringify({tuple:${JSON.stringify(tuple)},sourceNode:${JSON.stringify(version)},node:process.version,profiles:s.analysis.variants.filter(v=>v.resolverId==='node-runtime').map(v=>v.environment),bindings:s.analysis.bindings.length,extractorVersion:'fs-04/1',snapshotHash:createHash('sha256').update(JSON.stringify(s)).digest('hex'),rssBytes:process.memoryUsage().rss,checks:['offline','empty PATH','development tooling absent','two native profiles','resolver positive/negative','exports/events/workers','native TS erasure/type-only exclusion','duplicate CommonJS alias boundary','JSX native boundary','full/incremental']}));`;
    results.push(JSON.parse(execFileSync(executable,["--disable-warning=ExperimentalWarning","--input-type=module","--eval",probe],{cwd:resources,env:{PATH:"",NODE_ENV:"production",SystemRoot:process.env.SystemRoot,TEMP:process.env.TEMP,TMP:process.env.TMP},encoding:"utf8",timeout:120000})));
  }
  writeFileSync("docs/fs-05/evidence/node-preservation-packaged.json",JSON.stringify({platform:process.platform,arch:process.arch,runtime,executableHash:createHash("sha256").update(readFileSync(executable)).digest("hex"),harnessHash:createHash("sha256").update(readFileSync("scripts/fs-04-packaged.ts")).digest("hex"),nativeFixtureHash:createHash("sha256").update(nodeBytes).digest("hex"),nativeControlledSourceHash:createHash("sha256").update(JSON.stringify(nativeSources)).digest("hex"),fixtureHash:createHash("sha256").update(fixtureBytes).digest("hex"),results},null,2)+"\n");console.log(JSON.stringify(results));
}finally{assert(path.basename(directory).startsWith("cartograph FS04 packaged "));rmSync(directory,{recursive:true,force:true});}

