import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import assert from "node:assert/strict";

/** Developer-only pin generation from the previously verified approved closure. */
const audit = JSON.parse(readFileSync("docs/fs-07/evidence/package-audit.json", "utf8")) as {runtimeClosure: {name: string; version: string; dependencies: Record<string, string>; assets: {file: string; sha256: string; bytes: number}[]}[]};
assert.deepEqual(audit.runtimeClosure.map(p => [p.name, p.version]), [["hermes-parser", "0.25.1"], ["hermes-estree", "0.25.1"]]);
const manifest = JSON.stringify({version: 1, runtime: "hermes-parser@0.25.1", dependencies: audit.runtimeClosure}, null, 2) + "\n";
const hash = createHash("sha256").update(manifest).digest("hex");
mkdirSync("lib/engine/assets/flow", {recursive: true});
writeFileSync("lib/engine/assets/flow/runtime.json", manifest);
writeFileSync("lib/engine/adapters/flow-resource-pin.ts", `/** Approved Hermes runtime closure; generated by the opt-in FS-07 resource tool. */\nexport const FLOW_RESOURCE_PIN = "${hash}";\n`);
console.log("Pinned approved Flow runtime resource manifest", hash);
