import assert from "node:assert/strict";
import {readFileSync,writeFileSync,existsSync} from "node:fs";
import {createHash} from "node:crypto";
const prefix="docs/fs-04/evidence/",read=(file:string)=>JSON.parse(readFileSync(file,"utf8").replace(/^\uFEFF/,"")),hash=(file:string)=>createHash("sha256").update(readFileSync(file)).digest("hex");
const initial=read(prefix+"starting-inventory.json") as {head:string;files:{path:string;hash:string}[]};
const changed=initial.files.filter(f=>existsSync(f.path)&&hash(f.path)!==f.hash).map(f=>f.path),removed=initial.files.filter(f=>!existsSync(f.path)).map(f=>f.path);
const frozen=changed.filter(p=>/^(package.json|pnpm-lock.yaml|src-tauri\/Cargo|components\/|app\/|lib\/laya\/|lib\/ai\/|docs\/fs-0[0-3]\/)/.test(p));
assert.deepEqual(frozen,[]);assert.deepEqual(removed,[]);assert.equal(hash("lib/laya/laya-nav-1.json"),"aa499934b8197fb12c36eec2b367c523d5a6da77b439ab58dc4b30bb46ea3513");
writeFileSync(prefix+"preservation-audit.json",JSON.stringify({baselineHead:initial.head,changed,removed,frozenChanges:frozen,layaHash:hash("lib/laya/laya-nav-1.json")},null,2)+"\n");
const baseline=read(prefix+"baseline-results.json") as {id:string;exitCode:number;startedUtc?:string}[],post=existsSync(prefix+"post-verification.json") ? read(prefix+"post-verification.json") as {id:string;exitCode:number;startedUtc?:string}[] : [];
const latest=new Map([...baseline,...post].sort((a,b)=>Date.parse(a.startedUtc??"1970-01-01")-Date.parse(b.startedUtc??"1970-01-01")).map(r=>[r.id,r.exitCode])),pass=(...ids:string[])=>ids.every(id=>latest.get(id)===0);
const targets=read(prefix+"qualification-targets.json"),packaged=read(prefix+"packaged.json"),vite=read(prefix+"packaged-vite-preservation.json"),next=read(prefix+"next-oracles.json"),node=read(prefix+"node-oracles.json");
const erasure=read(prefix+"node-erasure-oracles.json");
assert.equal(targets.testHash,hash("tests/framework-support/fs-04.test.ts"));assert.equal(packaged.fixtureHash,hash("tests/fixtures/framework-support/F04-node-next/fixture.json"));
assert(next.every((r:{fixtureHash:string;outputHash:string;routes:unknown})=>r.fixtureHash===hash("tests/fixtures/framework-support/F04-node-next/fixture.json")&&r.outputHash===createHash("sha256").update(JSON.stringify(r.routes)).digest("hex")));
assert(node.every((r:{fixtureHash:string})=>r.fixtureHash===hash("tests/fixtures/framework-support/F04-node-next/node.json")));
const resources=read(prefix+"resource-measurements.json"),historical=read(prefix+"historical-performance.json"),acceptedHistorical=read("docs/fs-03/evidence/historical-performance.json");
const quantile=(values:number[],q:number)=>[...values].sort((a,b)=>a-b)[Math.ceil(values.length*q)-1];
type Measurement={elapsedMs:number;rssBytes:number;snapshotBytes:number;facts:number;files:number;deadlineHits:number};
type ResourceRow={tuple:string;group:string;peakCommittedBytes:number;peakRSSBytes:number;sample:{fixtureHash:string;measurements:Measurement[]}};
const stats=["next15","next16-preservation","next16-patch","node22","node24"].map(tuple=>{const rows=(resources.results as ResourceRow[]).filter(r=>r.tuple===tuple),cold=rows.filter(r=>r.group.startsWith("cold")).flatMap(r=>r.sample.measurements),warm=rows.filter(r=>r.group==="warm").flatMap(r=>r.sample.measurements);assert.equal(cold.length,5);assert.equal(warm.length,20);assert(rows.every(r=>r.sample.fixtureHash===hash(`tests/fixtures/framework-support/F04-node-next/${tuple.startsWith("node") ? "node" : "fixture"}.json`)));return {tuple,coldMedianMs:quantile(cold.map(r=>r.elapsedMs),.5),coldP95Ms:quantile(cold.map(r=>r.elapsedMs),.95),warmMedianMs:quantile(warm.map(r=>r.elapsedMs),.5),warmP95Ms:quantile(warm.map(r=>r.elapsedMs),.95),peakCommittedBytes:Math.max(...rows.map(r=>r.peakCommittedBytes)),peakRSSBytes:Math.max(...rows.map(r=>r.peakRSSBytes)),snapshotBytes:Math.max(...[...cold,...warm].map(r=>r.snapshotBytes)),maxFacts:Math.max(...[...cold,...warm].map(r=>r.facts)),deadlineHits:[...cold,...warm].reduce((sum,r)=>sum+r.deadlineHits,0)};});
const comparison={fs02FreshRatio:historical.freshRatio,fs02WarmRatio:historical.warmRatio,fs03FreshRatio:historical.medianFreshMs/acceptedHistorical.medianFreshMs,fs03WarmRatio:historical.medianWarmMs/acceptedHistorical.medianWarmMs};
writeFileSync(prefix+"resource-summary.json",JSON.stringify({stats,comparison,protocol:historical.protocol,limitations:["50 ms counter sampling can miss transient peaks","Small controlled fixtures do not establish worst-case whole-engine memory"]},null,2)+"\n");
const gates={fixture:pass("fs-04-tests"),oracles:next.length===9&&node.length===2&&erasure.length===2,profiles:pass("qualification")&&targets.results.length===13&&targets.results.every((r:{status:string})=>r.status==="PASS"),regression:pass("tests","fs-01-tests","fs-02-tests","fs-03-tests"),build:pass("next-typegen","typecheck","lint","next-build"),windows:pass("package-engine","assets","rust-format","rust-check","rust-tests","staged-smoke","fs-04-packaged","fs-03-packaged")&&packaged.harnessHash===hash("scripts/fs-04-packaged.ts")&&packaged.nativeFixtureHash===hash("tests/fixtures/framework-support/F04-node-next/node.json")&&packaged.results.length===5&&packaged.results.every((r:{checks:string[]})=>r.checks.includes("development tooling absent"))&&vite.results.length===2,baseline:pass("parse","map-counts","insights","engine","pilot-benchmark","diff-check"),performance:Object.values(comparison).every(r=>r<=1.2)&&stats.every(s=>s.deadlineHits===0),preservation:frozen.length===0};
const criteria:[string,string,(keyof typeof gates)[]][]=[
 ["04-01","Explicit package scopes, import/require extensions, ordered conditions, self/imports and external/workspace boundaries",["fixture","oracles","profiles"]],
 ["04-02","CJS exports/re-exports, mutation negatives, built-ins, type/runtime divergence",["fixture","oracles"]],
 ["04-03","Script/bin declarations, stable first-party HTTP/listen, EventEmitter and Worker associations",["fixture"]],
 ["04-04","App conventions/ownership, dynamic/catch-all paths, groups/private folders, slots/interceptions",["fixture","oracles"]],
 ["04-05","Static pageExtensions/basePath, source-root ownership and unsupported configuration",["fixture"]],
 ["04-06","Exported HTTP handlers/aliases/re-exports and distinct qualified derived HEAD/OPTIONS",["fixture","oracles"]],
 ["04-07","Pages API explicit comparisons/switches; unknown/mutable dispatch never guessed",["fixture"]],
 ["04-08","Client/server composition, directives/markers, prerendering and runtime conditions",["fixture"]],
 ["04-09","Module/inline actions, stable aliases/forms, client boundary/server calls; no invented action URL",["fixture"]],
 ["04-10","Version-specific Middleware/Proxy declarations and Edge execution boundary",["fixture","oracles"]],
 ["04-11","Ordered static redirects/rewrites, conditions, destinations and environment evidence",["fixture","oracles"]],
 ["04-12","Lifecycle/data exports and literal navigation/cache declarations",["fixture"]],
 ["04-13","UI-to-action and endpoint-to-service investigations retain boundary labels and witnesses",["fixture","windows"]],
 ["04-14","Determinism, full/incremental, snapshot v3 validation, storage/refresh and stale evidence",["fixture","regression","windows"]],
 ["04-15","Read-policy/security, no inspected code/config/plugins executed, cancellation/recovery",["fixture","regression","windows"]],
 ["04-16","Existing TS/JS, Next/Nest/Express/Docusaurus, Vite/React, exact Impact preserved",["regression","baseline","windows"]],
 ["04-17","Frozen Laya, completed UI, production dependencies and optional AI consent preserved",["preservation","regression"]],
 ["04-18","Typegen/typecheck/lint/build and asset/Rust/package verification",["build","windows"]],
 ["04-19","Cold/warm resource qualification and equivalent historical performance comparison",["performance"]],
 ["04-20","Per-pattern exact tuple/profile/hash ledger and recorded unsupported boundaries",["fixture","oracles","profiles","baseline"]]
];
const rows=criteria.map(([id,criterion,required])=>({id,criterion,status:required.every(g=>gates[g]) ? "PASS" : "FAIL",gates:required})),complete=rows.every(r=>r.status==="PASS");
writeFileSync("docs/fs-04/qualification.json",JSON.stringify({phase:"FS-04",status:complete ? "complete" : "incomplete",acceptanceSatisfied:complete,gates,criteria:rows,targets:targets.results,extractorVersion:"fs-04/1",testSourceHash:hash("tests/framework-support/fs-04.test.ts"),fixtureHashes:[hash("tests/fixtures/framework-support/F04-node-next/fixture.json"),hash("tests/fixtures/framework-support/F04-node-next/node.json")],oracleHashes:[hash(prefix+"next-oracles.json"),hash(prefix+"node-oracles.json")],packageHash:hash(prefix+"packaged.json"),patterns:criteria.slice(0,12).map(([id,scope,required])=>({id,scope,state:required.every(g=>gates[g]) ? "qualified" : "partial",record:complete ? hash(prefix+"qualification-targets.json") : null})),blockedTargets:targets.blocked,policy:"Qualifications cover named bounded patterns; aggregate capability remains partial. Missing/dynamic implementation evidence is a typed boundary, not a verified edge."},null,2)+"\n");
writeFileSync("docs/fs-04/acceptance.md",`# FS-04 acceptance ledger\n\nStatus: **${complete ? "complete" : "incomplete"}**. The table applies to the exact bounded qualification scope in [README](README.md); it does not grant a universal framework badge.\n\n| Criterion | Required behavior | Status | Evidence gates |\n| --- | --- | --- | --- |\n${rows.map(r=>`| ${r.id} | ${r.criterion} | ${r.status} | ${r.gates.join(", ")} |`).join("\n")}\n\nEvery gate links through [qualification.json](qualification.json) to retained records in \`evidence/\`. Baseline verification is in \`baseline-results.json\`; explicit corrections/reruns are in \`post-verification.json\`. Earlier failed logs remain retained. Controlled fixtures are authoritative; pinned public source is supplementary. Resource ratios and caveats are in [resource-budget.md](resource-budget.md).\n\nRemaining mandatory failures: ${rows.filter(r=>r.status!=="PASS").map(r=>r.id).join(", ")||"none"}. Known unsupported patterns remain explicitly documented in README and are not promoted to verified relationships. No FS-05 work, inspected application execution, Laya changes, commits, pushes or release publication.\n`);
console.log(JSON.stringify({complete,gates,comparison,criteria:rows.map(r=>[r.id,r.status])}));
