import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
const hash=(file:string)=>createHash("sha256").update(readFileSync(file)).digest("hex");
const initial=JSON.parse(readFileSync("docs/fs-06/evidence/starting-inventory.json","utf8")) as {head:string;files:{path:string;sha256:string}[]};
const current=execFileSync("git",["ls-files","--cached","--others","--exclude-standard","-z"]).toString().split("\0").filter(Boolean);
const starting=new Map(initial.files.map(f=>[f.path,f.sha256]));
const changed=current.filter(file=>existsSync(file)&&starting.has(file)&&hash(file)!==starting.get(file));
const added=current.filter(file=>existsSync(file)&&!starting.has(file));
const allowed=new Set(["lib/engine/adapters/composed.ts","lib/engine/adapters/python-worker.ts","lib/engine/parser-worker.ts","lib/model/framework.ts","lib/model/framework-validate.ts"]);
assert.deepEqual(changed.filter(file=>!allowed.has(file)),[],"Unexpected change to accepted worktree");
assert.equal(execFileSync("git",["rev-parse","HEAD"]).toString().trim(),initial.head,"No commit permitted");
assert.equal(hash("lib/laya/laya-nav-1.json"),"aa499934b8197fb12c36eec2b367c523d5a6da77b439ab58dc4b30bb46ea3513");
const protectedFiles=initial.files.filter(f=>/^(?:app\/|components\/|lib\/ai\/|lib\/laya\/)/.test(f.path));
for(const file of protectedFiles)assert.equal(hash(file.path),file.sha256,file.path);
const report={status:"PASS",head:initial.head,changed:changed.sort(),added:added.sort(),protectedFiles:protectedFiles.length,layaHash:hash("lib/laya/laya-nav-1.json"),note:"Difference from accepted FS-05 starting inventory, not from Git HEAD; ignored generated assets/oracles excluded. No UI/AI/Laya changes or commits; source-only supplementary archive never executed."};
writeFileSync("docs/fs-06/evidence/scope-audit.json",JSON.stringify(report,null,2)+"\n");
process.stdout.write(JSON.stringify({status:report.status,changed:changed.length,added:added.length,protectedFiles:protectedFiles.length})+"\n");
